name: esportevale
description: "O seu portal de atualizações sobre futebol!"
publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: lib/resource/esportevale_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: lib/resource/esportevale_logo.png
  min_sdk_android: 21
